### ISSUE TITLE
multiple specs in one summary show no images for all specs

### ISSUE THREAD

**Issue by l0-0l0-0l** [rdmueller/etka15#2]
Hi,

Did anyone try to use more than one specification? When I did, I only got the report-screenshots by geb for my first spec included in the summary-asciidoc-output. 

Should I put all my Test in one specification or is there a way to use multiple specs with screenshots for all of them?

_BTW: All screenshots are recorded and lie in the geb-folder as expected. They just don't get integrated in the html-report._

The ReportConverter.groovy scripts seems to work as the screenshot file-url's are written to the `gebReportInfo2.json`. However when I take a look at the spec's `*.ad`-reports only my first one has the paths to the images included.

I'll search for a fix but did never use asciidoc before, so if anybody has an idea I'd be glad ;-)

**Comment by rdmueller** [comment]
thanx for using my code and bringing this problem up.
I will try to supply a fix asap.

**Comment by rdmueller** [comment]
the `excel2spec.groovy` script and `EntwicklertagSpec.xml` is now prepared in such a way that it generates two specs. One in english and one in german.

Now I am able to reproduce your problem...

**Comment by rdmueller** [comment]
Please test. It should work by now.

**Comment by l0-0l0-0l** [comment]
I tested it and it works now. Thank you very much!
