### ISSUE TITLE
Summary shows 'null' for the Specification Stats

### ISSUE THREAD

**Issue by tweinreich** [rdmueller/etka15#3]
Mir ist ein kleiner Fehler im `summary-template.ad` (_Zeile 31_) aufgefallen. Ursache ist wohl eine Änderung durch [diesen commit](https://github.com/renatoathaydes/spock-reports/commit/ae66c67efe10ce7afb7925835c0b65242b1aa54d) im spock-reports repo. Danke das du deinen Code teilst, er hat mir bereits sehr gut beim Einstieg in Spock und Geb geholfen.

**Comment by rdmueller** [comment]
@tweinreich wenn ich so gutes Feedback bekomme ist es eine Win-Win Situation :-)

Der Change bei spock-reports war mir nicht aufgefallen - danke, fixe ich gleich
