### ISSUE TITLE
Is it possible to use your setup with Maven?

### ISSUE THREAD

**Issue by MehrCurry** [rdmueller/etka15#4]
For several reason i have to use maven. When trying to get things up i was facing this one:

```
groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at groovy.lang.Binding.getProperty(Binding.java:105)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
```

as in https://github.com/renatoathaydes/spock-reports/issues/67

As i see i am not able to use the filmStrip Monkey patch with maven, right?

Any hints what to try insteed?

**Comment by rdmueller** [comment]
hm. I guess it should be possible to set it up for maven, but I did't do it yet.

The Monkey patch was created for a grails project. maye it can removed.

let me check this.

**Comment by rdmueller** [comment]
ok. the monkey patch is needed.

Can you provide your maven.pom in a pull request? I will then try to make it work...

**Comment by MehrCurry** [comment]
My pom.xml contains tons of spring boot / spring cloud and other dependencies. May be a can strip it down to minimal setup to try things out.

**Comment by rdmueller** [comment]
I guess what you missed in the maven build was this file:
https://github.com/rdmueller/etka15/blob/master/gradle/filmStrip.gradle

**Comment by MehrCurry** [comment]
Ok, i will take a look Thank you.
